# Generated by Django 4.1.7 on 2023-08-18 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(default='null', max_length=100)),
                ('whatsapp', models.CharField(default='null', max_length=100)),
                ('account_email', models.CharField(default='null', max_length=100)),
                ('contact_email', models.CharField(default='null', max_length=100)),
                ('trip_option', models.CharField(default='null', max_length=100)),
                ('fly_class', models.CharField(default='null', max_length=100)),
                ('fly_continent', models.CharField(default='null', max_length=100)),
                ('city', models.CharField(default='null', max_length=100)),
                ('target_city', models.CharField(default='null', max_length=100)),
                ('other_cities', models.CharField(default='null', max_length=300)),
                ('number_of_passengers', models.IntegerField(default=0)),
                ('out_date', models.CharField(default='null', max_length=100)),
                ('back_date', models.CharField(default='null', max_length=100)),
                ('luggage', models.CharField(default='null', max_length=100)),
                ('max_price', models.CharField(default='null', max_length=100)),
                ('additional_information', models.TextField(default='null')),
                ('payment_advance_id', models.CharField(max_length=100)),
                ('payment_advance_status', models.CharField(default='Nie zapłacone', max_length=100)),
                ('payment_id', models.CharField(max_length=100)),
                ('payment_status', models.CharField(default='Nie zapłacone', max_length=100)),
            ],
        ),
    ]
