# Generated by Django 4.1.7 on 2023-08-18 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_advance_value',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_value',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
