# Generated by Django 4.1.7 on 2023-09-09 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_order_payment_advance_value_order_payment_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='number_of_offers',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(default='Nie określone', max_length=100),
        ),
    ]
