# Generated by Django 4.1.7 on 2023-09-11 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_alter_order_other_cities_alter_order_payment_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('name', models.CharField(default='null', max_length=100, primary_key=True, serialize=False)),
                ('background', models.CharField(default='null', max_length=100)),
                ('from_where', models.CharField(default='null', max_length=100)),
                ('to_where', models.CharField(default='null', max_length=100)),
                ('when', models.DateField(default='null', max_length=100)),
                ('transfers', models.IntegerField(default=None)),
                ('link', models.CharField(default='null', max_length=300)),
            ],
        ),
    ]
