# Generated by Django 4.1.7 on 2023-09-11 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='return_date',
            field=models.DateField(default='2020-01-01', max_length=100),
        ),
        migrations.AlterField(
            model_name='offer',
            name='when',
            field=models.DateField(default='2020-01-01', max_length=100),
        ),
    ]
