# Generated by Django 4.1.7 on 2023-09-12 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_offer_return_date_alter_offer_when'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='title',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
