# Generated by Django 4.1.7 on 2023-10-01 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_alter_order_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='back_date',
            field=models.CharField(blank=True, default='null', max_length=100, null=True),
        ),
    ]
